### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by dgenin** [nachovizzo/ros_in_docker#3]
Getting

```
Pulling ros (ros_in_docker/noetic:noetic)...
ERROR: pull access denied for ros_in_docker/noetic, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:33: build] Error 1
```

**Comment by nachovizzo** [comment]
Please read the instructions! you are missing step 3

just `make docker` and try

![image](https://user-images.githubusercontent.com/21349875/228510276-db60336b-2d6c-437d-981b-39ee6c3328db.png)

**Comment by dgenin** [comment]
Ah, sorry, i was following directions for vscode, which don't seem to have this step.

**Comment by nachovizzo** [comment]
You are right! My bad!
