### ISSUE TITLE
Permission issues when building

### ISSUE THREAD

**Issue by niklastkl** [nachovizzo/ros_in_docker#4]
Hello,
I run into a permission issue when I launch `make`. It returns the following:

> 
> Initializing catkin workspace in `/home/user/ros_ws`.
> [init] Error: Could not initialize catkin workspace: [Errno 13] Permission denied: '/home/user/ros_ws/.catkin_tools'
> make: *** [Makefile:33: build] Error 1

Building the container in VSCode works fine and I was not able to reproduce the error on a different machine. I tried to change the permission for the workspace folder within the Dockerfile manually, but that was not successful either.
Any help would be appreciated, thank you!

**Comment by nachovizzo** [comment]
Did you make docker first?

**Comment by niklastkl** [comment]
yes, and it seems to run without any issues (at least I get the same output as on my other machine)

**Comment by nachovizzo** [comment]
I haven't used this in years, so I can't figure out what's going on from your side

Sorry!

**Comment by niklastkl** [comment]
I understand, but thank you anyway!
